### ISSUE TITLE
Document build requirements

### ISSUE THREAD

**Issue by akopytov** [akopytov/sysbench#102]
Moving a request in #101 to a separate issue. It would be nice to have all build requirements in README.md, ideally with ready apt/yum commands for users to execute before building sysbench.

**Comment by nico-osd** [comment]
Hey,

I just built sysbench be1cf06df101508f5a6f007a2cc4a114837b9128 on el 7 and win 10.

Tested on oel7.3:
```sh
yum -y install automake make gcc libtool
./autogen.sh
./configure
make
```

As described in the README-WIN.txt: Visual Studio (incl. Visual C++ Components) and cmake is required in order to build the project. There might be another way without Visual Studio by using the build tools and the sdk. `cmake -G "Visual Studio <version> <year>"` for _version_ and _year_ run `cmake --help`  @akopytov: The biggest problem with the current commit (5df558c5090b889ef093b0c3c52d0ff1bc3c3491) on Windows is, that used header files (in sysbench.c) are actually not available on VS 2015 (ck_md.h, ck_cc.h, luajit.h). I took an the commit from two days ago and it worked fine (be1cf06df101508f5a6f007a2cc4a114837b9128).

I will test the yum packages on el6.8 as well and write an update.

Best.
N

**Comment by akopytov** [comment]
The master branch does not (and most likely never will) support Windows natively. You need the 0.5 branch, if you want a native Windows build: https://github.com/akopytov/sysbench/tree/0.5

Going forward, I think the only way to build and run sysbench on Windows will be WSL: https://en.wikipedia.org/wiki/Windows_Subsystem_for_Linux

But I don't have the capacity to test that at the moment.

**Comment by Scandalon** [comment]
> Going forward, I think the only way to build and run sysbench on Windows will be WSL: 
>But I don't have the capacity to test that at the moment.

I was able to compile (and run CPU test) on WSL!
Current Windows 10 Pro (1607, build 14393.693).
"sysbench 1.1.0-2343e4b (using bundled LuaJIT 2.1.0-beta2)"

Already had GCC installed, needed packages:
autoconf libtool pkg-config libmysqlclient-dev

**Comment by Scandalon** [comment]
Also, SmartOS! ( joyent_20161013T025521Z) in a native zone (base-64-lts 16.4.0), required:
automake make gcc libtool  gcc49 pkg-config gmake

So thank you to whoever did the configure/make scripts in such a way as to be more portable.

**Comment by akopytov** [comment]
Thanks for the summary!
