### ISSUE TITLE
Question about CPU benchmarking

### ISSUE THREAD

**Issue by kimh** [akopytov/sysbench#140]
**sysbench version**: `1.0.7`
**OS**: `macOS 10.11.6`

No matter where I ran `sysbench cpu run` I get very similar results like the following.

```
sysbench 1.0.7 (using bundled LuaJIT 2.1.0-beta2)

Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Prime numbers limit: 10000

Initializing worker threads...

Threads started!


General statistics:
    total time:                          10.0005s
    total number of events:              9083

Latency (ms):
         min:                                  0.96
         avg:                                  1.10
         max:                                  7.18
         95th percentile:                      1.34
         sum:                               9995.18

Threads fairness:
    events (avg/stddev):           9083.0000/0.00
    execution time (avg/stddev):   9.9952/0.00
```

I read some blog posts and all say that I should look at `total time` but it's always 10 sec in different platform/env. I also get the very similar result with very small prime number list e.g. `--cpu-max-prime=100` so now I'm puzzled what's the right command. I also run with `--time=0` and the benchmark never finishes.

My guess is the number refers to the value specified with `--time` option but then I don't know what's the right command to use.

Thanks in advance.

**Comment by kimh** [comment]
I got an expected behavior with `0.4`.

```

**Comment by akopytov** [comment]
You can limit either the total number of events (in which case, you should be looking at total time to measure performance), or the total execution time (in which case, you should be looking at the number of events, because the total time is constant). sysbench 1.0 limits by the total time by default, older versions had a default limit on the number of events.

In both cases, latency stats give you an idea about performance. That's the time it took to calculate prime numbers up to `--cpu-max-prime`. For example, total time divided by the average latency will give you the total number of executed loops (aka events).

Hope it makes sense.

**Comment by kimh** [comment]
> sysbench 1.0 limits by the total time by default, older versions had a default limit on the number of events.

Thank you for the answer. Yes, it makes sense.

What is an `event` in case of cpu? I assume the definition of an event differs depending on test suite. Is there any place I can find definition by myself?

**Comment by akopytov** [comment]
For each benchmark, an event is whatever is performed by the tests `execute_event` method. For the CPU benchmark, it is `cpu_execute_event()` which is a loop calculating all prime numbers up to `--cpu-max-prime`.

Closing for now, feel free to reopen if required.

**Comment by chengweiv5** [comment]
If it always limits in 10s by default for cpu testing, then what's the `--cpu-max-prime` used for? for example, even `--cpu-max-prime=1` will run for 10s.

Since the others results seems varies dramatically from time to time on the same machine just with different `--cpu-max-prime`, so I'm quite confused how to get the performance index.

e.g.

round 1, run with below command

```
# sysbench --threads=1 cpu --cpu-max-prime=1 run
sysbench 1.0.5 (using system LuaJIT 2.0.4)

Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Prime numbers limit: 1

Initializing worker threads...

Threads started!


General statistics:
    total time:                          10.0001s
    total number of events:              17526929

Latency (ms):
         min:                                  0.00
         avg:                                  0.00
         max:                                  0.21
         95th percentile:                      0.00
         sum:                               2859.25

Threads fairness:
    events (avg/stddev):           17526929.0000/0.00
    execution time (avg/stddev):   2.8593/0.00
```

round 2, just change `--max-cpu-prime` to 100

```
# sysbench --threads=1 cpu --cpu-max-prime=100 run
sysbench 1.0.5 (using system LuaJIT 2.0.4)

Running the test with following options:
Number of threads: 1
Initializing random number generator from current time


Prime numbers limit: 100

Initializing worker threads...

Threads started!


General statistics:
    total time:                          10.0001s
    total number of events:              4281484

Latency (ms):
         min:                                  0.00
         avg:                                  0.00
         max:                                  0.26
         95th percentile:                      0.00
         sum:                               8169.94

Threads fairness:
    events (avg/stddev):           4281484.0000/0.00
    execution time (avg/stddev):   8.1699/0.00
```

The first round says **total number of events:              17526929** while the second round says **total number of events:              4281484**, it's quiet different, if events means performance, why they're not the same or nearly the same?

Thanks in advance!

**Comment by akopytov** [comment]
`--cpu-max-prime` defines how much work is done per event. That is, a single event calculates all prime numbers up to the value of `--cpu-max-prime`.

You can then evaluate/compare performance by looking at the average latency, which is the average time it took CPU to execute a single event. Total number of events is also a metric of performance, if the total time is fixed.

Since this causes so much confusion, I should probably improve something in `cpu` reports to simplify things. If I change the report to print "events per second" or "prime numbers per second" would it make things easier to read?

**Comment by chengweiv5** [comment]
thanks @akopytov , `prime numbers per seconds` is better than `events per second` for me since event are changing if user changed `--cpu-max-prime`.

`prime numbers per seconds` somehow like the previously time cost by specified primes, I think it's much easier to understand.

Thank you again. :-)

**Comment by akopytov** [comment]
Well, prime numbers per second would also change with the `--cpu-max-prime` value. sysbench has to do some overhead work to execute events and collect statistics. So the higher `--cpu-max-prime` is, the more time is spent in event execution, and the less time is spent on overhead. So "primes per second" will also increase.

**Comment by KennethWilke** [comment]
Is this issue fixed? My team has been using the total time for various `--cpu-max-prime` and `--num-threads` settings and using total time as the primary output metric. But it seems the behavior has changed in the more recent version of sysbench.

**Comment by KennethWilke** [comment]
Ah, I see all our previous sysbench runs were with version ~`0.4.12`and the arguments and behavior have changed a lot since then. I suppose ubuntu just recently updated their repo to a newer version of sysbench and automation is suffering for it

**Comment by akopytov** [comment]
@KennethWilke yes, my fix for it was adding eps (events per second) statistics to cpu report to give a more intuitive metric: https://github.com/akopytov/sysbench/commit/b57453df606e0aa11a8b4d5e9c09b3698153b2f1

**Comment by coding-horror** [comment]
> older versions had a default limit on the number of events.

is there a syntax to replicate the old behavior (limit number of events, not time) on newer builds? This makes it a giant pain to compare with old results..

**Comment by KennethWilke** [comment]
@coding-horror to get it to run using the previous behavior, you'll want to add `--time=0` to run for an unspecified time, and `--events=10000` to run for 10k events (which is what previous versions had used as a limiter)

**Comment by heena30** [comment]
Hi

I am using sysbench-1.0.17-1.el7.centos.x86_64.rpm . Which is the latest version for sysbench today?

Thanks in advance

**Comment by zoliuton** [comment]
Fuck you akopytov "Since this causes so much confusion"

**Comment by bfanyuk** [comment]
Hello, @akopytov !
I have just experimented a bit with your tool and ran into the same confusion.
Looks like the issue here is lack of description about each individual metric.
Due to this thread I understood what is CPU test doing, how to tune it, and which numbers to look at. But for other metrics I will need to find another thread like this now.
What do you think about adding a short description here in GitHub about every metric:
1. What is this metric really testing.
2. What do numbers in the output mean (like event).
3. Which attributes can we use to tune this test and what they mean.

This would very much help. Also in further versions I would suggest also add this information into tool's output.

Thanks!
