### ISSUE TITLE
Can't read lua script from stdin

### ISSUE THREAD

**Issue by ghost** [akopytov/sysbench#155]
Hi Alexey,

I'm trying to run sysbench using the single dash option ('-'), which is supposed to be able to read a lua script from stdin. However, I can't seem to get it to work. Using the prime-test.lua script that I contributed a few days ago, it doesn't seem to do anything:

```bash
$ cat prime-test.lua | sysbench -
sysbench 1.0.7 (using bundled LuaJIT 2.1.0-beta2)

$ cat prime-test.lua | sysbench - run
sysbench 1.0.7 (using bundled LuaJIT 2.1.0-beta2)

$ cat prime-test.lua | sysbench - --cpu-max-prime=20000 --threads=1 --histogram run
sysbench 1.0.7 (using bundled LuaJIT 2.1.0-beta2)
```

Am I doing something wrong? I'm using homebrew sysbench 1.0.7 on Mac Sierra, by the way.

**Comment by akopytov** [comment]
Hi Tiago,

Yes, reading scripts from standard input was implemented mostly to be able to use sysbench as a regular Lua interperter. That is, to be able to execute arbitrary Lua scripts. In this mode, sysbench does not parse command line arguments, interpret commands or create any threads. It just does what a regular Lua interpreter would do: load a piece of code and execute.

Since your code only defines functions, but never calls them, it has no user-visible impact when executed in this mode.

Can you give more details about your use case? I.e. when executing a benchmark script (rather than a regular Lua script) from standard input might be useful?

**Comment by akopytov** [comment]
Closing as no feedback has been provided. Feel free to reopen.
