### ISSUE TITLE
Allow full path in require()

### ISSUE THREAD

**Issue by dimitrik-fr** [akopytov/sysbench#164]
Hi Alex,

if you don't mind, could you apply a small change within sb_lua.c in sb_lua_set_paths() function:

instead of:
```
  lua_pushliteral(L, "./?.lua;");  
  lua_pushliteral(L, "./?/init.lua;"); 
```

do:
```
  lua_pushliteral(L, "?.lua;");  
  lua_pushliteral(L, "?/init.lua;"); 
```
(e.g. remove "./" before the path) -- this will still allow to load local files from the current directory as before, but also allow a full path (if a full path used in the file name as a parameter to "require()")..

do you see any objection ?

Rgds,
-Dimitri

**Comment by akopytov** [comment]
Hi Dimitri,

I don't have any immediate objections to that change, my only concern is that it may break compatibility with some existing Lua packages that I'm going to use extensively in the future.

Generally, you have a number of options to load Lua code from arbitrary paths:

- set `LUA_PATH` before executing your script to whatever you want, and sysbench will honor that variable:

``` shell
LUA_PATH='/absolute/path/?.lua' ./my_custom_benchmark.lua
```
- set `package.path` in your script explicitly. The following will load `myscript.lua` from `/absolute/path`:

``` lua
package.path = "/absolute/path/?.lua" .. package.path
require "myscript"
```

- use `dofile("/absolute/path/myscript.lua")`, if executing some Lua code from another file is all you need, i.e. you don't actually need the package functionality where packages are searched in pre-defined locations

The default patterns being added by `sb_lua_set_paths()` are mostly for cases where I expect myself or other users to need frequently, i.e. they are there mostly for convenience

Unless you need to load from an absolute path frequently, e.g. in many scripts, I would suggest to use one of the above methods. Otherwise, I will implement the change and hope it won't break any third-party libraries.

What do you think?

Best regards,
Alexey.

**Comment by dimitrik-fr** [comment]
Hi Alexey,

I did not see you support "package.path" global variable ! -- this is a very valid point (while I was tweaking tests with LUA_PATH env setting, but having this out-of-the-box was looking more simple ;-))

well, I'll be fine with package.path, however the changes I proposed should not impact any existing tests as they are only for "./" (local path) - which is exactly valid without "./" prefix as well ;-))

Thanks a lot !!

Rgds,
-Dimitri

**Comment by dimitrik-fr** [comment]
BTW, would be great to document somewhere such kind of stuff ;-))

as well if you expose some "internal" variables (like current counter of executed events for a given thread, a given thread ID (or thread number), etc..) -- will be great to mention them too ;-)

Thanks again !

Rgds,
-Dimitri

**Comment by akopytov** [comment]
Cannot agree more, documenting the Lua API is still a debt I have to pay. I promise, that glorious that will come! :)

Closing this one for now.
