### ISSUE TITLE
Suggestion - Makefile should support DESTDIR

### ISSUE THREAD

**Issue by edrozenberg** [akopytov/sysbench#188]
A suggestion to make DESTDIR work during ```make install```.

I tried

```$ DESTDIR=/some/place make install```

and it didn't respect the DESTDIR - instead it installed directly into various locations.

**Comment by akopytov** [comment]
Hm, are you sure `DESTDIR` wasn't respected? sysbench uses autotools, so `DESTDIR` support should work. That's what `make distcheck` uses, for example, and it is a part of automated testing in Travis CI.

Also, I tried `DESTDIR=/tmp/sysbench make install` and got all files installed under `/tmp/sysbench/usr/local` (since sysbench was configured with `--prefix=/usr/local`).

**Comment by akopytov** [comment]
Feel free to reopen if there's a case where `DESTDIR` doesn't work.

**Comment by edrozenberg** [comment]
Thanks, I just retested and it worked fine. Maybe I had mistyped DESTDIR the previous time, not sure. If I run into any future issues will report back.
