### ISSUE TITLE
FATAL: Worker threads failed to initialize within 30 seconds!

### ISSUE THREAD

**Issue by hpolonsky** [akopytov/sysbench#225]
H I'm getting this error for 1024 threads
for --tables=183 --table_size=200000000 
does sysbench 1.0 has limitation how many tables and size of the tables

**Comment by akopytov** [comment]
Hi!

No, there's no such limitation, but I guess you are running the benchmark over TCP, and sysbench fails to create connections, because creating 1024 connections on the server side triggers SYN cookie flood protection in the kernel. If that's the case, you should see relevant messages in dmesg.

In which case the solution is raising `sysctl net.ipv4.tcp_max_syn_backlog` and `﻿sysctl net.core.somaxconn` and the `backlog` system variable in the MySQL configuration should help.

**Comment by akopytov** [comment]
Closing, feel free to reopen if there's indeed a problem to fix on the sysbench side.
