### ISSUE TITLE
oltp_rw creates duplicate insert keys with high thread counts

### ISSUE THREAD

**Issue by fxober** [akopytov/sysbench#253]
sysbench oltp_read_write --threads=64 --time=300 --tables=8 --skip_trx=on --table_size=250000000 --percentile=99 --db-driver=mysql --mysql-db=$ --mysql-user=root --mysql-password=$ --mysql-socket=$ --mysql-ignore-errors run >> $log 2>&1 

Our version of MySQL 8 is: 8.0.11
sysbench: 1.0.15
output:
Threads started!

FATAL: mysql_stmt_execute() returned error 1062 (Duplicate entry '125943991' for key 'PRIMARY') for query 'INSERT INTO sbtest6 (id, k, c, pad) VALUES (?, ?, ?, ?)'
FATAL: `thread_run' function failed: /usr/share/sysbench/oltp_common.lua:488: SQL error, errno = 1062, state = '23000': Duplicate entry '125943991' for key 'PRIMARY'
Error in my_thread_global_end(): 1 threads didn't exit
sysbench 1.0.15 (using bundled LuaJIT 2.1.0-beta2)

We have not customized oltp_rw.lua in any way.

We see this only with higher thread counts, this is using Optane SSDs (extremely fast SSDs) and Skylake CPUs (72 HT cores in total), running on 4.16.8 kernel (Spectre patched with retpoline). CentOS 7.5 build.

Thanks for the feedback.
Frank

**Comment by akopytov** [comment]
Hi @fxober,

Deadlocks are expected with `--skip-trx=on`, because transactions and MVCC is the only way to prevent this kind of errors (but you can ignore them with `--mysql-ignore-errors=1062`.

Suppose you have two sysbench threads executing the following sequence simultaneously:

```sql
DELETE FROM sbtest1 WHERE id=1;
INSERT INTO sbtest1 VALUES(1, ...); 
```

If done inside a transaction, one of the transactions will have to wait on a row-level lock, then fail with a deadlock. If each statement is executed as a single-statement transaction, a duplicate key error will occur.

The `--skip-trx` mode was implemented when people wanted to run some read-only workloads with all SELECTs as single-statement transactions.
