### ISSUE TITLE
execution time ignored when mysql stops responding

### ISSUE THREAD

**Issue by utdrmac** [akopytov/sysbench#280]
Two hosts. sysbench on A, mysql on B. sysbench is set to only run for 60s. After starting the script, use iptables on B to block return packets to A. This causes sysbench to stop checking the timer, for some reason.

The expectation here is that the timer is absolute. If the timer expires, the script should stop, regardless of whether or not mysql is functioning.

```
sysbench \
	/usr/share/sysbench/oltp_read_write.lua \
	--db-driver=mysql \
	--db-ps-mode=disable \
	--skip_trx=on \
	--mysql-user=sbuser \
	--mysql-password=sbPass1234# \
	--mysql-db=sysbench \
	--mysql-host=mysql1 \
	--mysql-ignore-errors=all \
	--tables=1 \
	--table_size=100000 \
	--report-interval=1 \
	--threads=1 \
	--time=60 \
	--events=0 \
	--rate=10 \
	run | grep tps

...
[ 62s ] thds: 1 tps: 0.00 qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 0.00 err/s: 0.00 reconn/s: 0.00
...
```

**Comment by utdrmac** [comment]
Drop packets back to server A: `[vagrant@mysql1 ~]$ sudo iptables -A OUTPUT -d 192.168.70.200 -j DROP`

After removing rules (`iptables -F`), sysbench will eventually re-establish connection and only then will the execution timer calculation be evaluated.

Again, the expectation is that the timer be evaluated all times.

**Comment by akopytov** [comment]
Yes, this is a known behavior, but it is hard to say whether it is expected or not. 

Suppose my system has a very long response time, let's say 10 seconds. And then I start sysbench with a short time limit, e.g. `--time=1`. So sysbench issues a request to the server, then the time limit comes. If sysbench forces an abort for all worker threads, they would report zero events. Which would not tell me anything useful about system performance, but would at least indicate something went wrong.

Now suppose the response time varies between 1 second and 10 seconds. I have two threads, time limit of 1 seconds. sysbench starts, issues two requests. Thread #1 gets a response within the time limit, thread #2 is aborted due to the time limit. sysbench reports 1 event with 1 second latency. Would that be an expected answer?

Currently, the timer is always evaluated. But instead of killing worker threads when the time limit comes, sysbench sets a flag which is checked by worker threads when they complete their currently in-flight events.

There's also the `--force-shutdown` option, which allows you to specify the number of seconds to wait after the `--time` limit expires. After that many seconds sysbench will kill worker threads. It will also report all unfinished events separately in the stats.

The latter is probably what you need if you expect worker threads to not wait for event completion.
