### ISSUE TITLE
why random(rand-type=gaussian) write faster than read?

### ISSUE THREAD

**Issue by raolei039** [akopytov/sysbench#324]
when I use the following command to test the random write and read:
1. sysbench memory --time=0 --threads=1 --memory-block-size=8G --memory-total-size=8G --memory-scope=global --memory-oper=read --memory-access-mode=rnd --rand-type=gaussian run.
2. sysbench memory --time=0 --threads=1 --memory-block-size=8G --memory-total-size=8G --memory-scope=global --memory-oper=write --memory-access-mode=rnd --rand-type=gaussian run.
I found the random write faster than read for memory. But isn't random reading usually faster than random writing?

**Comment by akopytov** [comment]
In my case, read benchmarks show higher numbers than write ones. But it depends on a lot of things. Unfortunately I don't have enough time to explaining all the gory details of interpreting benchmark results. 

If you think that discrepancy was caused by a defect in sysbench, please feel free to describe that problem and reopen this tissue.
