### ISSUE TITLE
better error hints for missing help command

### ISSUE THREAD

**Issue by hicqu** [akopytov/sysbench#78]
I work with Archlinux which is a very light-weight Linux distribution without lua by default. And when I try

sysbench --test=oltp help

nothing useful was printed. 
I struggled very hard and then I found some lua scripts in $HomeDir/share/sysbench. Oh, maybe I need lua!
And it was going ok after I installed that.

So, I think it's good to add more nice error hints when lua is not in system for green-hands? Thanks!

**Comment by akopytov** [comment]
The problem was not in Lua, because Lua is always bundled with sysbench, you don't have to install it separately.

The actual problem, as I understand, was that

- oltp.lua does not provide any help (i.e. does not define the `help()` function)
- sysbench prints nothing if the script doesn't provide any help. which is confusing.

oltp.l
