### ISSUE TITLE
FATAL: Worker threads failed to initialize within 30 seconds!

### ISSUE THREAD

**Issue by dcongee** [akopytov/sysbench#89]
你好（HI）
我在使用sysbench0.5版本，指定参数--num-threads=1000时，有时候能正常运行，有时候则会遇到错误（FATAL: Worker threads failed to initialize within 30 seconds!）。 当--num-threads=400或者200时，都不会有错误。我的理解的，sysbench在初始化线程时，如果超过30秒还没有成功，则会提示上述错误。建议初始化线程的超时时间用参数来控制。
正常来讲，30秒初始化1000个线程，时间足够，但是我没有更多的信息来排查初始失败的原因，仅仅只有“FATAL: Worker threads failed to initialize within 30 seconds!”。建议程序中，可以输出更多信息，用于排查 。
另外，对于这种错误：FATAL: unable to connect to MySQL server, aborting...
(last message repeated 2 times)
FATAL: error 2003: Can't connect to MySQL server on '10.8.192.15' (110)
PANIC: unprotected error in call to Lua API (Failed to connect to the database)
PANIC: unprotected error in call to Lua API (Failed to connect to the database)
也没有更多的信息来排查，为何会连接数库失败。 数据本身也可以正常访问的。

**Comment by akopytov** [comment]
Hi,

I'm not sure I understand a Google Translate version of the above text completely, but I guess you are running a MySQL benchmark over network, and it fails to initialize worker threads within 30 seconds.

So connecting to the server is a part of thread initialization, because we want to make sure all threads are ready to execute queries before starting the actual benchmark. Normally 30 seconds is enough to create even thousands connections of network. The only exception is when some kind of flood protection on the server host, so the kernel either throttles or blocks attempts to create too many connections in a short period of time.  You should check `dmesg` on the kernel machine. My experience is that in cases like this, just increasing the 30 seconds timeout will not help -- connections just get stuck indefinitely.

What needs to be done is tuning the kernel on the server machine. Try setting `net.ipv4.tcp_max_syn_backlog` and `net.core.somaxconn` are set to some large enough values. Make sure `'back_log` in the server configuration is also large enough.

**Comment by akopytov** [comment]
Closing for now. Feel free to reopen if you think there' something to be improved or fixed in sysbench.

**Comment by dcongee** [comment]
thank you!

**Comment by Ortimus** [comment]
I ran into a similar problem where in my thread_init(thread_id)  method I need to load some data from a table into an array.  I intend to use random values from this array to build up my query in function event(thread_id). I need to do this for 3 tables to build up my query - to create a long running randomized query to simulate potential client behavior.

I need thread_init() to be able to configurable so that I can complete my load in < 30s.

Is there setting to do  that. Or should I just compile the code with the timeout changed so that I can run my test ?

**Comment by akopytov** [comment]
@Ortimus The timeout is configurable in the `master` thread (aka 1.1.0) via the `--thread-init-timeout` option.

**Comment by Ortimus** [comment]
Thanks for the quick response! That solved my problem.
I was on sysbench 1.0.8, moving to sysbench 1.1.0-dcde0d9 solved the timeout issue.

Also saw your article on the differences between 0.5 and 1.0+ in terms of retrieving results from sql calls (https://fosdem.org/2017/schedule/event/sysbench/attachments/slides/1519/export/events/attachments/sysbench/slides/1519/sysbench.pdf) - so I need everything to move forward.

Thanks  lot for your help!
