### ISSUE TITLE
Is the test result  different when I run sysbench 0.4 and 0.5 in the same enviroment?

### ISSUE THREAD

**Issue by wangkirin** [akopytov/sysbench#9]
hi , I just started to use sysbench and i wonder if the test result will be different when I run sysbench 0.4 and 0.5 in the same enviroment (same machine and same os)?

**Comment by akopytov** [comment]
If we are talking about database tests, then both 0.4 and 0.5 generate exactly the same workloads with default OLTP setttings.

However, the CPU time consumed by sysbench itself may differ between 0.4 and 0.5. Since the database server is usually on the same machine where sysbench is running, one may see different results.

Generally it is not recommended to compare database results generated by different sysbench versions, even if they only differ in a minor version number (like 0.4.12 vs 0.4.13), or have been compiled from different git snapshots. As in, if you plan to perform a series of benchmarks to compare specific results, it's best to fix the sysbench binary which is used in all benchmark series.

**Comment by wangkirin** [comment]
thx!  you mean if i run `cpu` or `memory` or `file I/O` that might be different results?

**Comment by akopytov** [comment]
For cpu/memory/fileio there may be no differences in results, as the code is _mostly_ the same between 0.4 and 0.5. Still, it's better to be on the safe side and use same versions to be sure you are comparing apples to apples.
